### ISSUE TITLE
Transfer openapi-connector-template-generator into the Camunda Community Hub

### ISSUE THREAD

**Issue by christian-konrad** [camunda-community-hub/openapi-connector-template-generator#2]

**Comment by christian-konrad** [comment]
@camunda-community-hub/DevRel

**Comment by christian-konrad** [comment]
@camunda-community-hub/devrel I transfered this repo to the hub.

**Comment by xomiamoore** [comment]
Awesome, thank you! Looks good to me, I would recommend adding a badge for Lifecycle Stage and to clarify which Camunda products the repo is compatible with. More info here: https://github.com/Camunda-Community-Hub/community/blob/main/extension-lifecycle.md

**Comment by christian-konrad** [comment]
Thank you @xomiamoore, I added the badges
